### ISSUE TITLE
css selector 通配选择

### ISSUE THREAD

**Issue by rupertqin** [rupertqin/code-log#54]
```html
<div class="red-box">red</div>
<div class="green-box">green</div>
<div class="blue-box">blue</div>
<div class="box-yellow">yellow</div>
<div class="big-box-yellow">big yellow</div>
```

三种通配选择写法，$匹配结尾， ^匹配开头,  *匹配全局:
```css
div[class$="box"]{border: 1px solid #999;}
div[class^="box"]{color: red;}
div[class*="yellow"]{background: yellow;}
```
## example:
http://jsbin.com/dixuramote/edit?html,css,output
